### ISSUE TITLE
Full Prettier settings API

### ISSUE THREAD

**Issue by GollyJer** [RobinMalfait/prettier-eslint-code#10]
Hi Robbin,
Thanks for keeping this extension up to date! 🎉 
Full Prettier API settings would be icing on the cake.  🎂  

[Prettier Settings API](https://github.com/prettier/prettier#api)

**Comment by RobinMalfait** [comment]
Hi @GollyJer 

I've thought about this, bot most of them can be set via eslint rules.
But maybe I should add them just for the sake of completeness?

Let me know what you think.

**Comment by GollyJer** [comment]
There are times I open code and don't have .eslintrc.js and your plugin still applys formatting.

Is that correct?  Something else was going on? If not then having full prettier settings eliminates the need for other prettier extensions.

The [prettier-atom](https://atom.io/packages/prettier-atom) plugin added an "ESLint Integration" checkbox to the rest of their  prettier settings.  They expose all prettier and allow the user to turn on ESLint if desired.

**Comment by RobinMalfait** [comment]
It might be that it is the default formatting that is kicking in. If you don't have a .eslintrc file of any form. Do you see this in the bottom?

![](http://d.rbn.nu/zolq+) or with an X?

You can click on it to see more information, if there is an X.

**Comment by GollyJer** [comment]
Here's the best example I can provide.
I have VSCode's javascript formatting turned off and ESLint, shown in the console output, is not loaded.
![2017-04-16_10h59_24](https://cloud.githubusercontent.com/assets/689204/25072093/d8f43404-2294-11e7-9e8c-de10b28b6ab1.png)

And this single test.js file open from the desktop.
![2017-04-16_11h00_01](https://cloud.githubusercontent.com/assets/689204/25072103/fee4a0ea-2294-11e7-98a5-abf1e7089e79.png)

If I format the code,  `Shft+Alt+F`, the `<View>` tag moves correctly into position.  
Given the settings, I can't think of what else, besides Prettier ESLint, that could be formatting the code.

**Comment by RobinMalfait** [comment]
Ok strange, but I added the full prettier options support in version 0.7.0
