### ISSUE TITLE
0.7.1 not working.

### ISSUE THREAD

**Issue by GollyJer** [RobinMalfait/prettier-eslint-code#11]
Hi Robin,
Thanks again for your updates to this extension.  
0.7.1 doesn't seem to work. 🙁 The Prettier ESLint checkmark never shows up in the status bar.

If I downgrade to 0.6.1 everything works again.

Sorry to be so annoying.

**Comment by RobinMalfait** [comment]
@GollyJer Do you have any config set for `prettier` itself?
If so can you share your config, and show me what error the extension is giving?

**Comment by GollyJer** [comment]
Uninstalling and reinstalling fixed the problem.  Should have tried that first. 😛

**Comment by RobinMalfait** [comment]
Alright, feel free to report other bugs or feature requests!
