### ISSUE TITLE
"TypeError: Path must be a string. Received undefined"

### ISSUE THREAD

**Issue by AndrewRayCode** [RobinMalfait/prettier-eslint-code#12]
If I select some code in a javascript file and run Prettier via command-k command-f it only shows:

"TypeError: Path must be a string. Received undefined"

in the output. Happens with a selection or the whole file. I don't see a way to debug this an an end user.

**Comment by RobinMalfait** [comment]
What does your config look like in VScode?

**Comment by AndrewRayCode** [comment]
Nothing special I don't think?

    {
        "eslint.enable": true,
        "javascript.validate.enable": false,
        "editor.rulers": [80],
        "window.zoomLevel": 0,
        "workbench.editor.enablePreview": true,
        "workbench.editor.enablePreviewFromQuickOpen": false
    }

**Comment by RobinMalfait** [comment]
Do you have this problem when you open up a new VScode tab/window without saving the file? Prettier-eslint will try to find your eslint config based on the file location. If you don't have the file saved there is no file location. Could you check if that is the problem?

**Comment by AndrewRayCode** [comment]
https://github.com/esbenp/prettier-vscode works out of the box and has more stars. Unfortunately, this project shows up first in the VSCode extensions "prettier" search and shows more VSCode stars and downloads. Do you think you should close this project in favor of the other one? Might save some developer headaches.

**Comment by RobinMalfait** [comment]
I know, but I will only do that once it has been merged in the prettier namespace itself...

**Comment by notgiorgi** [comment]
Having the same issue, any solutions yet?
