### ISSUE TITLE
eslint --fix problom

### ISSUE THREAD

**Issue by cocody** [RobinMalfait/prettier-eslint-code#14]
I have  test.js 
```
function merge() {
  var ret = {};
  for (var i in arguments) {
    var m = arguments[i];
    for (var j in m) {
      ret[j] = m[j];
    }
  }
  return ret;
}

console.log(merge({ a: 123 }, { b: 456 }));
```

and I choose Airbnb mode with `eslint --init`

when I exec `eslint test.js --fix`

the `var` transform `const`

but...

`Format Document` is not transform, still `var`

For test, I set some rules in `.eslintrc.js`

```
rules: {
    'indent': [ 'error', 8 ]
  },
```
exec `Format Document`

it work! 

why `eslimt --fix` is not complete in `prettier-eslint-code`  ?

**Comment by RobinMalfait** [comment]
I have no idea, I use the prettier-eslint from here https://github.com/prettier/prettier-eslint
