### ISSUE TITLE
Doesn't install

### ISSUE THREAD

**Issue by mintyPT** [RobinMalfait/prettier-eslint-code#17]
I'm new to vs code. I try to install this from the list, the green button goes from "install" to "installing" and then simply goes back to "install". No idea why

**Comment by RobinMalfait** [comment]
That's not related to the plugin. Try restarting your vscode, or file an issue at vscode itself.

**Comment by mintyPT** [comment]
I restarted a couple of time. And nothing. Thanks, will do.
