### ISSUE TITLE
Not catching some rules

### ISSUE THREAD

**Issue by koddsson** [RobinMalfait/prettier-eslint-code#19]
Hey 👋 

I'm have some issues with `prettier-eslint-code` not catching all the errors in files a quick example is something like this:

<img width="442" alt="screen shot 2017-05-15 at 11 48 40" src="https://cloud.githubusercontent.com/assets/318208/26054540/deac3a86-3964-11e7-99d5-e09ec4706dfe.png">

Above the `prettier-eslint-code` doesn't catch that the function `foo` isn't used anywhere and that there is no such thing as `bar` in scope.

I thought maybe I had something mis-configured but the `eslint` CLI gives me the correct results.

<img width="592" alt="screen shot 2017-05-15 at 11 48 56" src="https://cloud.githubusercontent.com/assets/318208/26054592/1121f35c-3965-11e7-80c0-d2bb57ea939b.png">

I tried poking around the code but wasn't sure where or why this was happening.

**Comment by lukaszmoroz** [comment]
This extension only formats the code (i.e. runs it through `prettier` and `eslint --fix`). If you want error reporting from `eslint`, you still need [ESLint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) (with `eslint.autoFixOnSave` disabled).

**Comment by koddsson** [comment]
Oh man, I thought it did both! Thanks for the help @lukaszmoroz
