### ISSUE TITLE
Add option for filePath to eslint

### ISSUE THREAD

**Issue by guywaldman** [RobinMalfait/prettier-eslint-code#2]
Or alternatively, use `eslint.nodePath` in `settings.json` for VSCode.

P.S. Thank you for this great extension! Very much appreciated.

**Comment by RobinMalfait** [comment]
Q: what's the use case for this?

`prettier-eslint` will find the eslint config for you based on the filePath.

**Comment by guywaldman** [comment]
When you have `eslint` installed globally and don't want to add it as a local dep in a particular project.

**Comment by briandipalma** [comment]
Does this addon use the locally installed prettier/ESLint or does it bundle it's own?

**Comment by RobinMalfait** [comment]
@briandipalma I use a dependency called prettier-eslint by Kent C. Dodds https://github.com/prettier/prettier-eslint. I guess they install prettier & eslint as a dependency

**Comment by RobinMalfait** [comment]
You can now set the `prettier-eslint.eslintPath` via settings.

**Comment by GollyJer** [comment]
Hi again!  I'm still working through getting things set up correctly and ran into this issue... I think.

I have eslint installed globally via Yarn.
To get the vscode ESLint extension working I set:
`"eslint.nodePath": "C:\\Users\\Jeremy\\AppData\\Local\\Yarn\\config\\global\\node_modules"`
It works great.

However, after turning on the **prettier-eslint-code** extension it seems the code is being sent to **prettier**, but not **eslint --fix**.
Here's what it looks like.  Notice the linting errors but the checkbox next to **Prettier ESLint**.
![image](https://cloud.githubusercontent.com/assets/689204/24563727/750e96ba-161d-11e7-86c2-8363de186d64.png)

Adding the setting:
`"prettier-eslint.eslintPath": "C:\\Users\\Jeremy\\AppData\\Local\\Yarn\\config\\global\\node_modules"`
raises the error
`Error: Cannot find module 'C:\Users\Jeremy\AppData\Local\Yarn\config\global\node_modules'`

If I run the **eslint --fix** command by hand, it works.

Thanks again for the help!  It's so close to perfect. 😃

**Comment by RobinMalfait** [comment]
Hi @GollyJer 

Try replacing

`C:\Users\Jeremy\AppData\Local\Yarn\config\global\node_modules`

with:

`C:\Users\Jeremy\AppData\Local\Yarn\config\global\node_modules\eslint`

Does that help?

**Comment by GollyJer** [comment]
Hey.  Thanks again for all the help.  
That doesn't work either.  Same behavior. :-/
The eslint folder does exist in that path though.

**Comment by RobinMalfait** [comment]
And what happens if you don't set a path at all?

**Comment by GollyJer** [comment]
Same behavior.  That's what started me looking down this path.
I'm going to install eslint in the project to verify it works as expected that way.

**Comment by GollyJer** [comment]
Hey.  Wanted to jump back on here and say that when eslint is locally installed prettier-eslint-code works poerfectly.  For now, I'm just going to install eslint and eslint-airbnb (and it's 4 dependencies) in all my projects.   Thanks!

**Comment by RobinMalfait** [comment]
Okay cool, I am not on windows so I couldn't test that. But on mac you can link the global eslint and it works. Sorry for the inconvenience...
