### ISSUE TITLE
This extension isn't working correct with formatOnSave

### ISSUE THREAD

**Issue by tamj0rd2** [RobinMalfait/prettier-eslint-code#24]
Environment: Ubuntu 16.04
vscode version: 1.13.0

I have formatOnSave turned on, however I have to save the file twice in order for the document to be prettified.

Example:

Write the below code in a .js file and press save.

```js
let someFunc = () => {
// incorrectly indented line 1
// incorrectly indented line 2
  return 'Hello'
}
```

Expected code to be formatted to:
```js
let someFunc = () => {
  // incorrectly indented line 1
  // incorrectly indented line 2
  return 'Hello'
}
```

Code was actually not formatted and looked like below:
```js
let someFunc = () => {
// incorrectly indented line 1
// incorrectly indented line 2
  return 'Hello'
}
```

**Comment by charlesvinette** [comment]
I am having the same issue, but I suspect something is wrong with my config as I am a new VSCode user 😅

**Comment by tamj0rd2** [comment]
It was working fine for me up until roughly a week or 2 ago which is weird. I don't recall doing anything on my end that could have broke it.
On 15 Jun 2017, at 15:16, Charles <notifications@github.com<mailto:notifications@github.com>> wrote:

I am having the same issue, but I suspect something is wrong with my config as I am a new VSCode user 😅

**Comment by charlesvinette** [comment]
It is working if using the command palette though!

**Comment by tamj0rd2** [comment]
Yup! I think I'll go back to the cli until this is fixed though.

**Comment by GollyJer** [comment]
Hey Guys.
Try [this other Prettier extension.
](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)
If it has the same issue then your problem is interference from another installed extension.

**Comment by tamj0rd2** [comment]
@GollyJer Thanks. I've just given that one a try and it works without any issues.

Actually... now that I've installed that extension, uninstalled it, and reinstalled prettier-eslint vscode, it seems to be working perfectly. Really weird... Can we keep this open for a day or two just in case it happens again? I have a feeling it might.

**Comment by GollyJer** [comment]
Hey @tamj0rd2.
I'm just another user that happen to know the answer to your question. 😄 

As far as I know @RobinMalfait is thinking about merging this extension with the other one once it gets moved to the Prettier namespace in github.  You're probably more future proof if you keep Esben Petersen's version installed.

Hopefully they use Robin's images and iconography. 👍

**Comment by tamj0rd2** [comment]
@GollyJer Thanks for letting me know. This problem has cropped back up again, so I'll switch to the main Prettier extension once it has been integrated with eslint :)

**Comment by GollyJer** [comment]
@tamj0rd2 It is.
![screenshot_28](https://user-images.githubusercontent.com/689204/27289529-3d65e2dc-54d8-11e7-9f1c-e8f1fdfcfc12.png)

**Comment by tamj0rd2** [comment]
@GollyJer Oops, I didn't notice. Thanks again
