### ISSUE TITLE
Prettier Config Options

### ISSUE THREAD

**Issue by arialaurel** [RobinMalfait/prettier-eslint-code#3]
I've noticed that running prettier-eslint-code creates a different result than when I run prettier-eslint myself because my line length limits are longer than the default 80 and eslint --fix won't extend them back after prettier shortens them.

Would you accept a PR that added prettier config options to this plugin?

**Comment by arialaurel** [comment]
Sorry, just saw that these get inferred from the eslint config so there's really no need for this. I had just typoed my line length rule so it wasn't getting picked up by eslint or the inferring logic.

**Comment by RobinMalfait** [comment]
Hehe it happens. I will accept PRs if needed ;)
