### ISSUE TITLE
Reformatting of multi-line, chained function calls on a single line

### ISSUE THREAD

**Issue by devilleweppenaar** [RobinMalfait/prettier-eslint-code#4]
Works great!

The only issue I've come across is where it puts chained function calls on the same line.

I've confirmed that this is likely due to prettier,  as manually running the 'ESLint: Fix all auto-fixable Problems' command doesn't result in this format change.

Any idea why it would reformat:
```javascript
describe('root', () => {
	it('should have GET for health check', done => {
		request.get('/')
			.expect(200)
			.end(done);
	});
});
```

into this:
```javascript
describe('root', () => {
	it('should have GET for health check', done => {
		request.get('/').expect(200).end(done);
	});
});

?

**Comment by RobinMalfait** [comment]
It does that because there is enough 'room' to put it all on 1 line.

I think you can use [newline-per-chained-call](http://eslint.org/docs/rules/newline-per-chained-call): `newline-per-chained-call: ["error", { "ignoreChainWithDepth": 2 }]` eslint rule to fix it (not tested though).

Let me know if this helps! :)

**Comment by devilleweppenaar** [comment]
Thanks @RobinMalfait! That did the trick. Didn't even think to check if there's an ESLint rule.

Thanks again for this awesome project!

**Comment by devilleweppenaar** [comment]
Unfortunately I spoke too soon. :(

After more testing I can confirm that the issue still persists.

I tried different settings for the 'newline-per-chained-call' ESLint option, but although the editor underlined the issue, it still insisted in reformatting the code into 1 line.

For reference, we are using [AirBnb's ESLint config](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/style.js) as a base, and they set the option as follows: `'newline-per-chained-call': ['error', { ignoreChainWithDepth: 4 }],`.

**Comment by RobinMalfait** [comment]
@devillexio Maybe you can get more information regarding this issue in the https://github.com/prettier/prettier-eslint repo. Since that's what the plugin uses to make your code pretty
