### ISSUE TITLE
How to enforce printWidth setting

### ISSUE THREAD

**Issue by 0x80** [RobinMalfait/prettier-eslint-code#6]
In vscode settings I put `"prettier.printWidth": 80,` and also in eslintrc I've set max-len like you see below, but still if I hit format the 80 characters limit is not enforced. What am I doing wrong?

```json
{
  "extends": [
    "plugin:flowtype/recommended",
    "plugin:react/recommended"
  ],
  "plugins": [
    "flowtype",
    "react"  
  ],
  "parserOptions": {
    "ecmaVersion": 2016,
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "env": {
    "es6": true,
    "node": true
  },
  "rules": {
    "max-len": ["error", 80]
  }
}
```

**Comment by RobinMalfait** [comment]
`prettier.printWidth` should suffice. Could you share a little example project to reproduce the bug?

**Comment by 0x80** [comment]
While creating an isolated example project I found out that printWidth worked when I put it in the workspace settings file. Turns out I had another printWidth set to 120 somewhere lower in my user settings 🙈

**Comment by RobinMalfait** [comment]
Hehe, @0x80 it happens. Hope you enjoy the plugin!
