### ISSUE TITLE
prettier-eslint was upgraded to v5.1

### ISSUE THREAD

**Issue by GollyJer** [RobinMalfait/prettier-eslint-code#9]
I know you probably know already but I thought I'd make an issue just in case. 😃 

prettier-eslint has been [upgraded to 5.1](https://github.com/prettier/prettier-eslint/releases/tag/v5.1.0) which now includes Prettier 1.0.

**Comment by RobinMalfait** [comment]
I did not know it, thanks for the reminder! Updating now...
